remote_theme: galette/theme-ghpages
title: Galette Stripe
description: Plugin to handle membership fees and donations payments with Stripe
author: Guillaume AGNIERAY
maintainer: community
plugin:
  name: Stripe
  archive: galette-plugin-stripe
  min_galette: "1.3.0"
defaults:
  - scope: {path: ""}
    values: {layout: default}
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
