INSTALLDIR = $(shell pwd)
LANGUAGES = `find ./ -name "stripe_*.po" -print | sed 's|^\./stripe_\(.*\).po|\1|'`
DOMAINS = stripe
PHP_SOURCES = $(sort $(shell find ../ -maxdepth 1 -name \*.php)) \
              $(sort $(shell find ../lib/GaletteStripe/ -name \*.php)) \
              $(sort $(shell find ../tempcache -name \*.twig))

all : extract mo

twig :
	cd ../../../../ && bin/console galette:twig-cache $(shell basename $(abspath $(CURDIR)/..)) && cd ${INSTALLDIR}

po :
	@echo "Generating PO files:"
	@for l in ${LANGUAGES}; do \
	  for d in ${DOMAINS}; do \
	    if [ -f $${d}_$${l}.po ]; then \
	      echo -n "  Updating $${d}_$${l}.po"; \
	      msgmerge -U $${d}_$${l}.po $$d.pot >/dev/null ; \
	    else \
	      echo "  Creating of $${d}_$${l}.po"; \
	      msginit -o $${d}_$${l}.po -i $$d.pot >/dev/null ; \
	    fi; \
	  done \
	done

mo :
	cd ../../../../ && bin/console galette:compile-locales plugin-stripe

extract : twig ${PHP_SOURCES} Makefile
	xgettext ${PHP_SOURCES} --keyword=_T:1,2t --keyword=__:1,2t --keyword=_Tn:1,2,4t --keyword=_Tx:1c,2,3t --keyword=_Tnx:1c,2,3,5t -L PHP --from-code=UTF-8 --add-comments=TRANS --msgid-bugs-address=translations@galette.eu --force-po -o ${DOMAINS}.pot;
	cd ../../../../ && bin/console galette:twig-pot-references $(CURDIR)/${DOMAINS}.pot $(shell basename $(abspath $(CURDIR)/..))
	echo "Generating en_US:"
	@for d in ${DOMAINS}; do \
	  sed 's/charset=CHARSET/charset=UTF-8/' $$d.pot | LANG=C msginit --no-translator -i - --locale=en_US.utf8 -o $${d}_en_US.po; \
	done
